### ISSUE TITLE
Hackpad becomes whackpad

### ISSUE THREAD

**Issue by nikosprodro** [hackpad/hackpad#47]
<a href="https://github.com/dokterbob"><img src="https://avatars2.githubusercontent.com/u/22742?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dokterbob](https://github.com/dokterbob)**
_Sun Jan  8 13:13:41 2017_
_Originally opened as https://github.com/dropbox/hackpad/issues/67_

----

Whackpad is a community fork of the Hackpad web-based realtime wiki, based on the open source EtherPad collaborative document editor, which again is a fork of etherpad.

As Hackpad had been unmaintained by Dropbox since 2015, we decided to create a fork to allow contributions to be gathered to keep the codebase alive. If you wish to join the community, please join us on #hackpad on #freenode or #whackpad:chat.weho.st on [Matrix/Riot](https://riot.im/app/#/room/whackpad:chat.weho.st).

**Comment by pors** [comment]
And it becomes hackpad again :)
