### ISSUE TITLE
Making a new Hackpad works fine within a page but not from the menu

### ISSUE THREAD

**Issue by erwblo** [hackpad/hackpad#65]

**Comment by erwblo** [comment]
When you try it from the menu you're being moved to the frontpage of Hackpad.

**Comment by nikosprodro** [comment]
This is probably due to a redirect error (from https to http), we have now added proper checks, sitewide, in order to avoid faulty redirects. See 1f43a8e553b00fe04b9f38eb9f8fae5a2bc846d9

Closing issue
