### ISSUE TITLE
Make emoji support part of the build process

### ISSUE THREAD

**Issue by pors** [hackpad/hackpad#69]
Emoji support seems not "on" by default as the `etherpad/src/static/img/emoji/unicode/` directory is empty. The readme inside says:

> To get emoji support:
> Go to https://github.com/github/gemoji/tree/master/images/emoji/unicode
> and copy the images into this directory.

That doesn't exist anymore, but we can recreate the images with https://github.com/github/gemoji

**Comment by nikosprodro** [comment]
Did not make adding emojies part of the build process, it is just 2MB of images so we just added them in the specified folder
